### ISSUE TITLE
Authentication in a SPA: Token refresh best practice research

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/authentication-server-examples#4]
See discussions on https://github.com/noi-techpark/mobility-analytics/issues/29

We need to refresh a token from time to time, such that a webapp (SPA) user gets not kicked out after the token expires. 

What are the best practices in such cases?
What does the Keycloak community think about it?

**Comment by alexlanz** [comment]
Maybe a useful link: https://github.com/keycloak/keycloak-documentation/blob/master/securing_apps/topics/oidc/javascript-adapter.adoc

**Comment by Piiit** [comment]
Solved with the vanilla-spa example... Thx
